version: "3.3"
services:
  #FRONT-END
  frontend:
    build: ./frontend
    image: frontend
    stdin_open: true
    env_file:
      - ./frontend/.env
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - VITE_API_BASE_URL=http://localhost:5003
      - VITE_API_PORT=5003
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - mern-app
    depends_on:
      - backend

  #BACK-END
  backend:
    build: ./backend
    image: backend
    env_file:
      - ./backend/.env
    ports:
      - 5003:5003
    environment:
      - CHOKIDAR_USEPOLLING=true
      - PORT=5003
      - MONGO_URL=mongodb://mongo:27017/sharenergy
      - MIGRATE_dbConnectionUri=mongodb://mongo:27017/sharenergy
      - LOCALE=pt-br
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongo
    networks:
      - mern-app
    entrypoint: ./docker-entrypoint.sh
  #MONGO-DB
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/db
    networks:
      - mern-app
networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local
